export const ActionTypes = {
	SET_ALL_LINKS: "SET_ALL_LINKS",
	ADD_NEW_LINK: "ADD_NEW_LINK",
	DELETE_A_LINK: "DELETE_A_LINK",
	UPDATE_A_LINK: "UPDATE_A_LINK",
	UPDATE_PUBLIC_FLAG: "UPDATE_PUBLIC_FLAG",
	CREATE_USER: "CREATE_USER",
	LOGIN_USER: "LOGIN_USER",
	LOGGED_IN: "LOGGED_IN",
	LOGGED_OUT: "LOGGED_OUT",
	IS_AUTHORIZED: "IS_AUTHORIZED",
	GET_USER: "GET_USER",
}
